/** Demo tags shown on a challenge card until `ChallengeEntity` exposes a `tags` field from the API. */
export const CHALLENGE_DEMO_TAGS: Array<string> = [
    "#NodeJS",
    "#React",
    "#NextJS",
    "#TailwindCSS",
    "#TypeScript",
    "#JavaScript",
    "#HTML",
    "#CSS",
    "#Python",
    "#Java",
    "#C++",
    "#C#",
    "#PHP",
    "#Ruby",
    "#Swift",
    "#Kotlin",
    "#Go",
    "#Rust",
    "#Scala",
    "#Haskell",
    "#OCaml",
    "#Erlang",
    "#Elixir",
    "#F#",
    "#Dart",
    "#Flutter",
    "#React Native",
    "#React Native",
]
