// @ts-check
// Autogenerated from the folder structure of `.claude/` (design/, rules/, skills/…).
// A new doc or a new folder shows up in the sidebar the moment the file lands in
// `.claude/**` — no manual wiring, matching the "single source in .claude/" goal.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  canon: [{ type: "autogenerated", dirName: "." }],
}

module.exports = sidebars
